### ISSUE TITLE
Wrong `.bg_bg\.surface` token

### ISSUE THREAD

**Issue by FlatMapIO** [cschroeter/park-ui#245]
The `styles.css` generated by the panda cli in my park-ui project contains the wrong token: 

<img width="344" alt="image" src="https://github.com/cschroeter/park-ui/assets/1720349/b834a213-2782-4aea-803e-d98de535dfc7">

```css
  .bg_bg\.surface {
    background: bg.surface;
}

```

I've searched the park-ui and panda sources and still can't determine the source of the error.
