### ISSUE TITLE
Tooltip arrow not visible

### ISSUE THREAD

**Issue by wagnerpaz** [cschroeter/park-ui#411]
```jsx
<Tooltip.Root closeDelay={0} openDelay={0}>
  <Tooltip.Trigger asChild>
    <Info />
  </Tooltip.Trigger>
  <Tooltip.Positioner>
    <Tooltip.Content>
      <Tooltip.Arrow>
        <Tooltip.ArrowTip />
      </Tooltip.Arrow>
      I am a tooltip!
    </Tooltip.Content>
  </Tooltip.Positioner>
</Tooltip.Root>
```
there are two undefined CSS variables. If I provide a value it works

```css
:root {
  --arrow-size: 8px;
  --arrow-background: #fff;
}
```
